// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBipn1I5VokmmoYBn9uHRu-SHokv3qv4Pk',
    appId: '1:903655692062:web:5ceaea818311497f10db0f',
    messagingSenderId: '903655692062',
    projectId: 'digital-wellbeing-44244',
    authDomain: 'digital-wellbeing-44244.firebaseapp.com',
    storageBucket: 'digital-wellbeing-44244.appspot.com',
    measurementId: 'G-580F8PJTSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_q1firn9uRj1wrfVzipvsMhgSeQe11GI',
    appId: '1:903655692062:android:7e13498c5c1ef0a710db0f',
    messagingSenderId: '903655692062',
    projectId: 'digital-wellbeing-44244',
    storageBucket: 'digital-wellbeing-44244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUt_uPlbc5kt3nfLueFiYflwUNMMQwd4',
    appId: '1:903655692062:ios:0479a8ca43f27c7910db0f',
    messagingSenderId: '903655692062',
    projectId: 'digital-wellbeing-44244',
    storageBucket: 'digital-wellbeing-44244.appspot.com',
    iosBundleId: 'com.example.digitalWellbeing',
  );
}
